// <auto-generated />
using System;
using Curatarr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curatarr.Data.Migrations
{
    [DbContext(typeof(CuratarrDbContext))]
    partial class CuratarrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Curatarr.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SonarrId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SonarrId")
                        .IsUnique();

                    b.HasIndex("SeriesId", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Curatarr.Models.EpisodeFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId", "Side")
                        .IsUnique();

                    b.ToTable("EpisodeFiles");
                });

            modelBuilder.Entity("Curatarr.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RadarrId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RadarrId")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Curatarr.Models.MovieFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId", "Side")
                        .IsUnique();

                    b.ToTable("MovieFiles");
                });

            modelBuilder.Entity("Curatarr.Models.MovieSubtitleFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId", "Side", "Suffix")
                        .IsUnique();

                    b.ToTable("MovieSubtitleFiles");
                });

            modelBuilder.Entity("Curatarr.Models.OrphanedDestinationFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "RelativePath")
                        .IsUnique();

                    b.ToTable("OrphanedDestinationFiles");
                });

            modelBuilder.Entity("Curatarr.Models.OrphanedMovieFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId", "RelativePath")
                        .IsUnique();

                    b.ToTable("OrphanedMovieFiles");
                });

            modelBuilder.Entity("Curatarr.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SonarrId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SonarrId")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Curatarr.Models.SubtitleFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId", "Side", "Suffix")
                        .IsUnique();

                    b.ToTable("SubtitleFiles");
                });

            modelBuilder.Entity("Curatarr.Models.Episode", b =>
                {
                    b.HasOne("Curatarr.Models.Series", "Series")
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Curatarr.Models.EpisodeFile", b =>
                {
                    b.HasOne("Curatarr.Models.Episode", "Episode")
                        .WithMany("Files")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Curatarr.Models.MovieFile", b =>
                {
                    b.HasOne("Curatarr.Models.Movie", "Movie")
                        .WithMany("Files")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Curatarr.Models.MovieSubtitleFile", b =>
                {
                    b.HasOne("Curatarr.Models.Movie", "Movie")
                        .WithMany("Subtitles")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Curatarr.Models.OrphanedDestinationFile", b =>
                {
                    b.HasOne("Curatarr.Models.Series", "Series")
                        .WithMany("OrphanedDestinationFiles")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Curatarr.Models.OrphanedMovieFile", b =>
                {
                    b.HasOne("Curatarr.Models.Movie", "Movie")
                        .WithMany("OrphanedDestinationFiles")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Curatarr.Models.SubtitleFile", b =>
                {
                    b.HasOne("Curatarr.Models.Episode", "Episode")
                        .WithMany("Subtitles")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Curatarr.Models.Episode", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Subtitles");
                });

            modelBuilder.Entity("Curatarr.Models.Movie", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("OrphanedDestinationFiles");

                    b.Navigation("Subtitles");
                });

            modelBuilder.Entity("Curatarr.Models.Series", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("OrphanedDestinationFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
